version: '2.1'
services:

  ra-main-door:
    build: 
      context: room-assistant
      dockerfile: Dockerfile
    network_mode: host
    restart: always
    labels:
      io.balena.features.dbus: 1 
    ports:
      - 6425:6425  
      - 6415:6415

  doorbell:
    build: 
      context: doorbell
      dockerfile: Dockerfile
    privileged: true
    labels:
      io.balena.features.dbus: 1 
    restart: always
    ports:
      - 5555:5555
    volumes:
      - 'pulse:/run/pulse'

  browser:
    image: bh.cr/balenalabs/browser-aarch64 # where <arch> is one of aarch64, arm32 or amd64
    privileged: true # required for UDEV to find plugged in peripherals such as a USB mouse
    ports:
        - '5011' # management API (optional)
        - '35173' # Chromium debugging port (optional)
    volumes:
      - 'settings:/data' # Only required if using PERSISTENT flag (see below)

  audio:
    image: bh.cr/balenalabs/audio-rpi # where <arch> is one of rpi, armv7hf, aarch64 or amd64
    privileged: true
    labels:
      io.balena.features.dbus: 1  # Only required for bluetooth support
    ports:
      - 4317:4317                 # Only required if using PA over TCP socket
    volumes:
      - 'pulse:/run/pulse'        # Only required if using PA over UNIX socket

volumes:
  settings:
  pulse:
