version: '2.1'
services:

  ra-main-door:
    build: 
      context: room-assistant
      dockerfile: Dockerfile
    network_mode: host
    restart: always
    labels:
      io.balena.features.dbus: 1 
    ports:
      - 6425:6425  
      - 6415:6415

  doorbell:
    build: 
      context: doorbell
      dockerfile: Dockerfile
    privileged: true
    labels:
      io.balena.features.dbus: 1 
    restart: always
    devices:
      - /dev/dri
    group_add:
      - video
    volumes:
      - x11:/tmp/.X11-unix
    # depends_on:
    #   - xserver
    ports:
      - 8000:8000
      - 80:80
    # command: >
    #   bash -c "python -m main"
    # command: >
    #   bash -c "cd /usr/src/app 
    #     && python -m main"


  xserver:
    image: balenablocks/xserver
    restart: always
    privileged: true
    volumes:
      - x11:/tmp/.X11-unix
    # depends_on:
    #   - doorbell

volumes:
  x11:

