#:kivy 1.11.0
# __author__ = 'sintefocean'

<ContentBase>:
    orientation: 'horizontal'
    # canvas.before:
    #     Color:
    #         rgba: 1, 0, 0, 1
    #     Rectangle:
    #         pos: self.pos
    #         size: self.size
    canvas.before:
        Color:
            # rgba: app.theme_cls.bg_dark
            rgba: 0,0,0,1
        Rectangle:
            pos: self.pos
            size: self.size
