#:kivy 1.11.0
# __author__ = 'sintefocean'

<ContentBase>:
    # canvas.before:
    #     Color:
    #         rgba: app.theme_cls.bg_light
    #         # rgba: 0,0,0,1
    #     Rectangle:
    #         pos: self.pos
    #         size: self.size
    # canvas.before:
    #     Color:
    #         rgba: app.kelvin[3000]
    #     Rectangle:
    #         pos: self.pos
    #         size: self.size

