setup:
    qos: 0
    ssl: False

bell:
    command_topic: "bell/ring/toggle"

doors:
    main:
        name: Front
    garage:
        name: Garasje
    workshop:
        name: Verksted


garage:
    command_topic: "garage/gate/cmd"
    state_topic: "garage/gate/state"
    state: "Unknown"

mode:
    command_topic: "house/mode/cmd"
    state_topic: "house/mode/state"
    state: "Unknown"

state:
    command_topic: "house/state/cmd"
    state_topic: "house/state/state"
    state: "Unknown"