


class BELL_COMMAND_PAYLOAD():
    DO="do"

class DOORLOCK_COMMAND_PAYLOAD():
    LOCK="LOCK"
    UNLOCK="UNLOCK"

class DOORLOCK_STATUS_PAYLOAD():
    LOCKED="LOCKED"
    UNLOCKED="UNLOCKED"


class GARAGE_COMMAND_PAYLOAD():
    OPEN="OPEN"
    CLOSE="CLOSE"
    STOP="STOP"

class GARAGE_STATUS_PAYLOAD():
    OPEN="open"
    OPENING="opening"
    CLOSED="closed"
    CLOSING="closing"


ACCESS_TIMEOUT = 5*60
LOGIN_TIMOUT = 2*60
CONTROL_TIMEOUT = 1*60

PIN_SIZE = 4


SCREEN_WIDTH = 800
SCREEN_HEIGHT = 480
LEFT_BOX_WIDTH = SCREEN_HEIGHT
RIGHT_BOX_WIDTH = SCREEN_WIDTH - LEFT_BOX_WIDTH