ARG PYTHON_VERSION_MAJOR
ARG PYTHON_VERSION_MINOR
ARG PIP_VERSION

FROM balenalib/raspberrypi3-64-python:${PYTHON_VERSION_MAJOR}.${PYTHON_VERSION_MINOR}

ARG PYTHON_VERSION_MAJOR
ARG PYTHON_VERSION_MINOR
ARG PIP_VERSION
ARG PYTHON_VERSION=$PYTHON_VERSION_MAJOR.$PYTHON_VERSION_MINOR

RUN apt update

RUN install_packages \
    xserver-xorg-core \
    # xserver-xorg \
	xinit \
    # xterm \
	# x11-xserver-utils \
	libmtdev-dev \
	libsdl2-dev \
	libsdl2-image-dev \
	libsdl2-mixer-dev \
	libsdl2-ttf-dev \
	mesa-common-dev \
	git-core \
	build-essential \
	python${PYTHON_VERSION_MAJOR}-dev \
	python${PYTHON_VERSION_MAJOR}-setuptools \
	python${PYTHON_VERSION_MAJOR}-opengl \
	libjpeg-dev \
	libpng-dev
	# libglib2.0-dev \
	# bluez \
	# bluetooth \
	# libbluetooth-dev \
	# python${PYTHON_VERSION_MAJOR}-bluez \
	# libcap2-bin


RUN python -m pip install --upgrade \
	pip \
	wheel \
	setuptools

# RUN setcap 'cap_net_raw,cap_net_admin+eip' "$(readlink -f "$(which python3)")"

COPY requirements.txt ./
RUN python -m pip install --no-cache-dir -r requirements.txt

RUN echo "#!/bin/bash" > /etc/X11/xinit/xserverrc \
  && echo "" >> /etc/X11/xinit/xserverrc \
  && echo 'exec /usr/bin/X -s 0 dpms -nocursor -nolisten tcp "$@"' >> /etc/X11/xinit/xserverrc

# RUN echo 'SUBSYSTEM=="backlight",RUN+="/bin/chmod 666 /sys/class/backlight/%k/brightness /sys/class/backlight/%k/bl_power"' | sudo tee -a /etc/udev/rules.d/backlight-permissions.rules

RUN mkdir -p /usr/src/app/
WORKDIR /usr/src/app
ENV KIVY_HOME=/usr/src/app
COPY config.ini config.ini

COPY ./app /usr/src/app/
COPY start.sh ./

CMD ["bash", "start.sh"]